### PR TITLE
Removing private Information

### PR DESCRIPTION
**Pull request by ItzN00bPvP**
removed private information i dont want to get ddosed by script kids again isnt fun for me and everyone else who want to play on the server

### CODE REVIEW

**Review by Windowsk — COMMENTED** [review]
goober

**Review by oriyadid — CHANGES_REQUESTED** [review]
I think you forgor the metal pipe, for reference check out #22

**Comment by LiveOvertroll** [comment]
do you even understand why i posted this here?

**Comment by Shrecknt** [comment]
> do you even understand why i posted this here?

to annoy people?

**Pull request closed without merging**
