### PR TITLE
Fix leak

### PR DESCRIPTION
**Pull request by Meesterbouwer123**
it's designed to be a challenge, with this information only griefers will join, and the server will die out

### CODE REVIEW

**Comment by PainfulPaladins** [comment]
yea, please don't leak the server ip

**Comment by LiveOvertroll** [comment]
griefer can not join i thought because of the proxy?

**Comment by Meesterbouwer123** [comment]
griefers can still join, but will probably be banned of the proxy soon
and they can always go back with an alt

**Comment by PainfulPaladins** [comment]
yea

**Comment by Meesterbouwer123** [comment]
so i think this pr should be merged
(or this repo be removed entirely)

**Pull request closed without merging**
