### PR TITLE
Super important leak

### PR DESCRIPTION
**Pull request by oriyadid**
Oh and by the way LO's base coordinates are `174000  -42781`, overworld.

### CODE REVIEW

**Comment by Windowsk** [comment]
> Oh and by the way LO's base coordinates are `174000 -42781`, overworld.

liar, everyone knows the base is at 3

**Review by Windowsk — APPROVED** [review]
Solid leak, 10/10

**Comment by Shrecknt** [comment]
https://user-images.githubusercontent.com/58538423/220435639-1c936ee9-0e3b-42a5-9efb-fd92916191bf.mp4

**Comment by Windowsk** [comment]
> 

can you make it louder? I can't hear it

**Comment by LiveOvertroll** [comment]
wow seems correct going to check it later on the server

**Comment by LiveOvertroll** [comment]
wrong information

**Comment by veronoicc** [comment]
Just wanna say that this is definetely real, however i recently also got there and we (the moles) blew up the base a second time. Please keep this leak here so nobody needs to do the coord finding shit

**Pull request closed without merging**
